name: Publich

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup dotnet7
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 7.0.x
        
    #- name: install dotnet maui
    #  run: 
    #    dotnet workload install maui

    - name: restore
      run: 
        dotnet restore ./client/client.service &&
        dotnet restore ./server/server.service
        #dotnet restore ./client/client.service.app
        
    - name: publish projects
      run: ./publish.bat "C:\\Android\\android-sdk"

    - name: get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    
    - name: create release
      id: create_release
      uses: GongT/actions-recreate-release@v1
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        tag_name: v2.1.0.1-beta
        release_name: v2.1.0.1-beta.${{ steps.date.outputs.today }}
        draft: false
        prerelease: false
        
    - name: upload any
      id: upload-any
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-any.zip
        asset_name: p2p-tunnel-any.zip
        asset_content_type: application/zip
    
    - name: upload win x64 single
      id: upload-win-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-win-x64-single.zip
        asset_name: p2p-tunnel-win-x64-single.zip
        asset_content_type: application/zip
    
    - name: upload win arm64 single
      id: upload-win-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-win-arm64-single.zip
        asset_name: p2p-tunnel-win-arm64-single.zip
        asset_content_type: application/zip

    - name: upload linux x64 single
      id: upload-linux-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-linux-x64-single.zip
        asset_name: p2p-tunnel-linux-x64-single.zip
        asset_content_type: application/zip
    
    - name: upload linux arm64 single
      id: upload-linux-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-linux-arm64-single.zip
        asset_name: p2p-tunnel-linux-arm64-single.zip
        asset_content_type: application/zip
        
    - name: upload osx x64 single
      id: upload-osx-x64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-osx-x64-single.zip
        asset_name: p2p-tunnel-osx-x64-single.zip
        asset_content_type: application/zip
    
    - name: upload osx arm64 single
      id: upload-osx-arm64
      uses: actions/upload-release-asset@master
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./public/publish-zip/p2p-tunnel-osx-arm64-single.zip
        asset_name: p2p-tunnel-osx-arm64-single.zip
        asset_content_type: application/zip

    #- name: upload apk
    #  id: upload-apk
    #  uses: actions/upload-release-asset@master
    #  env:
    #      GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
    #  with:
    #    upload_url: ${{ steps.create_release.outputs.upload_url }}
    #    asset_path: ./public/publish-zip/p2p-tunnel.apk
    #    asset_name: p2p-tunnel.apk
    #    asset_content_type: application/vnd.android.package-archive
        
